name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
        echo "DATABASE_URL=sqlite:///./test.db" >> .env
        echo "CONSUL_HOST=consul" >> .env
        echo "CONSUL_PORT=8500" >> .env
        echo "CONSUL_ENABLED=true" >> .env
        echo "SERVICE_PORT=8080" >> .env
        echo "KONG_DATABASE=postgres" >> .env
        echo "KONG_PG_HOST=kong-database" >> .env
        echo "KONG_PG_USER=kong" >> .env
        echo "KONG_PG_PASSWORD=kongpass" >> .env

    - name: Build TodoApp Docker image
      run: |
        cd ToDoApp
        docker build -t todoapp:latest .

    - name: Build NotificationService Docker image
      run: |
        cd NotificationService
        docker build -t notification-service:latest .

    - name: Build Kong image
      run: |
        docker pull kong:3.3.1

    - name: Save Docker images
      run: |
        docker save todoapp:latest > todoapp.tar
        docker save notification-service:latest > notification-service.tar
        docker save kong:3.3.1 > kong.tar

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "todoapp.tar,notification-service.tar,kong.tar,docker-compose.yml,.env,setup-kong-dirs.sh,kong/"
        target: "/opt/todoapp"

    - name: Start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /opt/todoapp
          docker load < todoapp.tar
          docker load < notification-service.tar
          docker load < kong.tar
          docker-compose up -d
          chmod +x kong-setup.sh
          # Wait for Kong to be ready before running setup
          sleep 30
          ./kong-setup.sh